site_name: ARMxy Developer Center
site_description: Official documentation for ARMxy industrial edge gateways

# 主题：material 工业文档美观主题，外网展示效果好
theme:
  name: material

# 导航栏目录，和你仓库 docs 下文件一一对应
nav:
  - Home: index.md
  - Getting Started:
      - Introduction: getting-started/introduction.md
      - test: getting-started/test.md
  - Node-RED:
      - 第1篇：快速装好Node-RED，在ARMxy上跑通你的第一个节点: node-red/First acquaintance.md
  - Industrial Protocol:
      - Modbus: protocol/modbus.md

extra_css:
  - assets/custom.css
