site_name: 钡铼技术文献资料
site_description: Official documentation for ARMxy industrial edge gateways

# 主题：material 工业文档美观主题，外网展示效果好
theme:
  name: material
  palette:
    # 亮色模式下代码块自动深色
    - scheme: default
      primary: indigo
      accent: blue
# 导航栏目录，和你仓库 docs 下文件一一对应
nav:
  - Home: index.md
  - Getting Started:
      - Introduction: getting-started/introduction.md
      - test: getting-started/test.md
  - Node-RED:
      - 第1篇：快速装好Node-RED，在ARMxy上跑通你的第一个节点: node-red/First-acquaintance.md
      - 第2篇：Node-RED基础节点全掌握实战教程（Inject、Debug、Switch、Function）: node-red/02-node-red.md
      - 第3篇：Node-RED常用功能节点盘点及社区节点安装: node-red/03-node-red.md
  - Industrial Protocol:
      - Modbus: protocol/modbus.md

extra_css:
  - assets/custom.css

extra_javascript:
  - https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit
