site_name: 

site_description: Official documentation for ARMxy industrial edge gateways

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

nav:
  - Home: index.md

  - Getting Started:
      - Introduction: getting-started/introduction.md
      - Test: getting-started/test.md

  - Node-RED:
      - Overview: node-red/overview.md

  - Industrial Protocol:
      - Modbus: protocol/modbus.md
